[supervisord]
nodaemon=true
user=appuser
logfile=/var/www/html/storage/logs/supervisord.log
pidfile=/var/www/html/storage/logs/supervisord.pid

[program:php-fpm]
command=php artisan serve --host=0.0.0.0 --port=8001
autostart=true
autorestart=true
stdout_logfile=/var/www/html/storage/logs/php-fpm.log
stderr_logfile=/var/www/html/storage/logs/php-fpm.err.log

[program:queue-worker]
command=php artisan queue:work --tries=1 --sleep=1
autostart=true
autorestart=true
numprocs=1
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/var/www/html/storage/logs/queue-worker.log
stderr_logfile=/var/www/html/storage/logs/queue-worker.err.log